name: CI/CD

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  REPO_NAME: ${{ secrets.ARTIFACT_REPO_NAME }}
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_LOCATION: ${{ secrets.GKE_LOCATION }}

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: prediction_service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: prediction_service
        run: pytest -q

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.CI_SA_EMAIL }}

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and push image
        working-directory: .
        env:
          IMAGE: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/fraud-prediction:${{ github.sha }}
        run: |
          docker build -t "$IMAGE" -f prediction_service/Dockerfile .
          docker push "$IMAGE"

      - name: Export image ref
        run: echo "image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/fraud-prediction:${{ github.sha }}" >> $GITHUB_OUTPUT
        id: image

  deploy:
    runs-on: ubuntu-latest
    needs: [test-and-build]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.CI_SA_EMAIL }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --location ${{ env.GKE_LOCATION }} --project ${{ env.PROJECT_ID }}

      - name: Update image in deployment
        run: |
          IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/fraud-prediction:${{ github.sha }}"
          sed -i "s#REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/fraud-prediction:latest#$IMAGE#g" k8s/deployment.yaml

      - name: Apply manifests
        run: kubectl apply -f k8s/
